export const GET_CATEGORIES_TOTAL_COUNT = "GET_CATEGORIES_TOTAL_COUNT";
export const SET_SHOW_CATEGORIES = "SET_SHOW_CATEGORIES";
export const SET_SHOW_CREATE_CATEGORY = "SET_SHOW_CREATE_CATEGORY";
export const SET_SHOW_UPDATE_CATEGORY = "SET_SHOW_UPDATE_CATEGORY";
export const CATEGORY_CREATED = "CATEGORY_CREATED";
export const CATEGORY_UPDATED = "CATEGORY_UPDATED";
export const CATEGORY_DELETED = "CATEGORY_DELETED";
export const SET_CATEGORY = "SET_CATEGORY";
