export const GET_ORDERS_TOTAL_COUNT = "GET_ORDERS_TOTAL_COUNT";
export const GET_TOTAL_PROFIT = "GET_TOTAL_PROFIT";
export const GET_AVG_MONTHLY_PROFIT = "GET_AVG_MONTHLY_PROFIT";
export const GET_LINE_CHART_DATA = "GET_LINE_CHART_DATA";
export const GET_PIE_CHART_DATA = "GET_PIE_CHART_DATA";
export const SET_SHOW_ORDERS = "SET_SHOW_ORDERS";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDER_PRODUCTS = "FETCH_ORDER_PRODUCTS";
export const FETCH_ORDER_CUSTOMER_DETAILS = "FETCH_ORDER_CUSTOMER_DETAILS";
export const FETCH_ORDER_DETAILS = "FETCH_ORDER_DETAILS";
export const FETCHING_ORDERS_ADMIN = "FETCHING_ORDERS_ADMIN";
export const FETCHING_ORDER_PRODUCTS = "FETCHING_ORDER_PRODUCTS";
export const FETCHING_ORDER_DETAILS = "FETCHING_ORDER_DETAILS";
export const FETCHING_ORDER_CUSTOMER_DETAILS =
  "FETCHING_ORDER_CUSTOMER_DETAILS";
export const ORDER_UPDATED = "ORDER_UPDATED";
export const FETCH_ORDER_BY_ID = "FETCH_ORDER_BY_ID";
