export const ADMIN_LOGIN = "ADMIN_LOGIN";
export const ADMIN_LOGIN_ERROR = "ADMIN_LOGIN_ERROR";
export const VALIDATE_ADMIN_LOGIN = "VALIDATE_ADMIN_LOGIN";
export const VALIDATE_ADMIN_LOGIN_ERROR = "VALIDATE_ADMIN_LOGIN_ERROR";
export const GET_USERS_TOTAL_COUNT = "GET_USERS_TOTAL_COUNT";
export const ADMIN_LOG_OUT = "ADMIN_LOG_OUT";
