export const SET_INITIAL_QUERY = "SET_QUERY";
export const SET_CATEGORY_NAME_FOR_SHOP = "SET_CATEGORY_NAME_FOR_SHOP";
export const SET_QUERY_BACK_TO_DEFAULT = "SET_QUERY_BACK_TO_DEFAULT";
export const CLICK_ON_PRODUCT_PAGE = "CLICK_ON_PRODUCT_PAGE";
export const SET_IS_ON_ADMIN_AREA = "SET_IS_ON_ADMIN_AREA";
export const SET_ACTIVE_SLIDE = "SET_ACTIVE_SLIDE";
